### ISSUE TITLE
Опечатки ML_System_Design_Doc_Template.md, ML_System_Design_Doc_Workflow.md 

### ISSUE THREAD

**Issue by Hitriihoma** [IrinaGoloshchapova/ml_system_design_doc_ru#3]
Опечатки в текстах

1.  [ML_System_Design_Doc_Template.md](https://github.com/IrinaGoloshchapova/ml_system_design_doc_ru/blob/main/ML_System_Design_Doc_Template.md) 
[2.3. Этапы решения задачи `Data Scientist`](https://github.com/IrinaGoloshchapova/ml_system_design_doc_ru/blob/main/ML_System_Design_Doc_Template.md#23-%D1%8D%D1%82%D0%B0%D0%BF%D1%8B-%D1%80%D0%B5%D1%88%D0%B5%D0%BD%D0%B8%D1%8F-%D0%B7%D0%B0%D0%B4%D0%B0%D1%87%D0%B8-data-scientist)
> Этап 4 - Интеграция бизнес правил для расчета бизнес-метрик качества мрдели

мрдели -> модели (заменить "р" на "о")

3. [ML_System_Design_Doc_Workflow.md](https://github.com/IrinaGoloshchapova/ml_system_design_doc_ru/blob/main/ML_System_Design_Doc_Workflow.md)
> Техника. Data Scientist, ответственный за продукт, заполняет остальное. Все вопросы, которые возникают у Data Scientist к бизнесу в процессе заполнения дока, пишем прям в документе

прям в документе -> прямо в документе (добавить "о")

**Comment by promsoft** [comment]
Спасибо большое, опечатки исправили!
